durations:
  - minutes: 5
    label: '5 minutes'
  - minutes: 10
    label: '10 minutes'
  - minutes: 15
    label: '15 minutes'
  - minutes: 20
    label: '20 minutes'
  - minutes: 30
    label: '30 minutes'
  - minutes: 45
    label: '45 minutes'
  - minutes: 60
    label: '1 hour'
    default: true
  - minutes: 90
    label: '90 minutes'
  - minutes: 120
    label: '2 hours'
  - minutes: 180
    label: '3 hours'
  - minutes: 240
    label: '4 hours'
  - minutes: null
    label: 'All Day'
